language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - DB=pgsql POSTGRESQL_VERSION=9.4

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database testing;' -U postgres
  - composer self-update
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs -n --extensions=php --standard=PSR2 ./src/ ./tests/

notifications:
  email: false
  hipchat:
    rooms:
      - secure: "RbslpmNVJmJJkdo8wLTuxWIJYm6b7blWYSYV4OUCcx/OPj5tk8v0U4h0KqYOgSpZ9t00l9NF9cDjNyUPly45FKChetJIO0ncF+SA680mglXU5HHuR/07ypKBsvBP+tVzI2crc24Uw7q+mgijJppKdp4fwcXIdc2M6I3wtkzXc4A="
    template:
    - "BUILD #%{build_number} - <b>%{repository}</b> (<i>%{commit} (%{branch}): <u>%{author}</u></i>): %{message} (See more: <a href=\"%{build_url}\">Details build</a> / <a href=\"%{compare_url}\">Changeset diff<a>)"
    format: html

matrix:
  allow_failures:
  - php: 7.0